apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name:  spring-boot-app-route
spec:
  to:
    kind: Service
    name: spring-boot-app
  port:
    targetPort: 8081
  tls:
    termination: edge
  wildcardPolicy: None
