---
- name: Configure Jenkins Server
  hosts: all
  become: yes
  gather_facts: true
  roles:
    - postgres
    - oc_cli
    - SonarQube
    - Git
    - Jenkins
    - Docker

    
  tasks:
    - name: Display Jenkins IP
      debug:
        msg: "Jenkins server: http://{{ ansible_host }}:8080"
        
    - name: Display sonarqube IP
      debug:
        msg: "SonarQube server: http://{{ ansible_host }}:9000 , First time Login Credentials: (user: 'admin', password: 'admin')"

